version: '3'
services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - ./hls:/usr/src/app/hls
    networks:
      - nginx_proxy
  
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - nginx_proxy

  ffmpeg:
    container_name: ffmpeg
    build:
      context: ./ffmpeg
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    volumes:
      - ./hls:/hls
    depends_on:
      - nginx
    networks:
      - nginx_proxy

networks:
  nginx_proxy: